<?php
/**
 * @file
 * A block module that displays Orcid Login.
 */
 
 /**
 * Implements hook_help().
 *
 * Displays help and module information.

 */
function orcid_developement_help($path, $arg) {
    switch ($path) {
        case "admin/help#orcid_developement":
            return '<p>' . t("Displays links to Orcid Login") . '</p>';
            break;
    }
}

/**
 * Implements hook_block_info().
 */
function orcid_developement_block_info() {
    $blocks['orcid_developement'] = array(
        // The name that will appear in the block list.
        'info' => t('Orcid Login'),
        // Default setting.
        'cache' => DRUPAL_CACHE_PER_ROLE,
    );
    return $blocks;
}


/**
 * Implements hook_menu().
 */
function orcid_developement_menu() {
    $items = array();
    $items['admin/config/user/orcid_developement'] = array(
      'title' => 'Orcid Loign',
      'description' => 'Configuration for Login module',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('orcid_developement_form'),
      'access arguments' => array('access administration pages'),
      'type' => MENU_NORMAL_ITEM,
    );
  
    return $items;
}


/**
 * Page callback: Latest posts settings
 *
 * @see latest_posts_form()
 */
function orcid_developement_form($form, &$form_state) {
    $form['orcid_developements_limit'] = array(
      '#type' => 'textfield',
      '#title' => t('Maximum number of posts'),
      '#default_value' => variable_get('orcid_developement_limit', 3),
      '#size' => 2,
      '#maxlength' => 2,
      '#description' => t('Login Form.'),
      '#required' => TRUE,
    );
  
    return system_settings_form($form);
}